import Foundation

enum TweakCatalog {
    static let all: [Tweak] = dock

    static let dock: [Tweak] = [
        Tweak(id: "dock.autohide-delay",
              title: "Instant Dock reveal",
              subtitle: "No pause before the Dock slides out",
              category: .dock,
              domain: "com.apple.dock",
              key: "autohide-delay",
              onValue: .float(0),
              restart: .dock),
        Tweak(id: "dock.autohide-time-modifier",
              title: "Faster Dock animation",
              category: .dock,
              domain: "com.apple.dock",
              key: "autohide-time-modifier",
              onValue: .float(0.15),
              restart: .dock),
        Tweak(id: "dock.no-bouncing",
              title: "No launch bounce",
              category: .dock,
              domain: "com.apple.dock",
              key: "no-bouncing",
              onValue: .bool(true),
              offValue: .bool(false),
              restart: .dock),
        Tweak(id: "dock.magnification",
              title: "Disable magnification",
              category: .dock,
              domain: "com.apple.dock",
              key: "magnification",
              onValue: .bool(false),
              restart: .dock),
        Tweak(id: "dock.showhidden",
              title: "Dim hidden apps",
              subtitle: "Fades icons of apps you have hidden",
              category: .dock,
              domain: "com.apple.dock",
              key: "showhidden",
              onValue: .bool(true),
              offValue: .bool(false),
              restart: .dock),
        Tweak(id: "dock.show-recents",
              title: "Hide recent apps",
              category: .dock,
              domain: "com.apple.dock",
              key: "show-recents",
              onValue: .bool(false),
              offValue: .bool(true),
              restart: .dock)
    ]
}
