import Foundation

enum TweakCatalog {
    static let all: [Tweak] = dock + finder + screenshots + speed + typing

    static let dock: [Tweak] = [
        Tweak(id: "dock.autohide-delay",
              title: "Instant Dock reveal",
              subtitle: "No pause before the Dock slides out",
              category: .dock,
              domain: "com.apple.dock",
              key: "autohide-delay",
              onValue: .float(0),
              restart: .dock),
        Tweak(id: "dock.autohide-time-modifier",
              title: "Faster Dock animation",
              category: .dock,
              domain: "com.apple.dock",
              key: "autohide-time-modifier",
              onValue: .float(0.15),
              restart: .dock),
        Tweak(id: "dock.no-bouncing",
              title: "No launch bounce",
              category: .dock,
              domain: "com.apple.dock",
              key: "no-bouncing",
              onValue: .bool(true),
              offValue: .bool(false),
              restart: .dock),
        Tweak(id: "dock.magnification",
              title: "Disable magnification",
              category: .dock,
              domain: "com.apple.dock",
              key: "magnification",
              onValue: .bool(false),
              restart: .dock),
        Tweak(id: "dock.showhidden",
              title: "Dim hidden apps",
              subtitle: "Fades icons of apps you have hidden",
              category: .dock,
              domain: "com.apple.dock",
              key: "showhidden",
              onValue: .bool(true),
              offValue: .bool(false),
              restart: .dock),
        Tweak(id: "dock.show-recents",
              title: "Hide recent apps",
              category: .dock,
              domain: "com.apple.dock",
              key: "show-recents",
              onValue: .bool(false),
              offValue: .bool(true),
              restart: .dock)
    ]

    static let finder: [Tweak] = [
        Tweak(id: "finder.AppleShowAllFiles",
              title: "Show hidden files",
              category: .finder,
              domain: "com.apple.finder",
              key: "AppleShowAllFiles",
              onValue: .bool(true),
              offValue: .bool(false),
              restart: .finder),
        Tweak(id: "finder.AppleShowAllExtensions",
              title: "Show all file extensions",
              category: .finder,
              domain: "NSGlobalDomain",
              key: "AppleShowAllExtensions",
              onValue: .bool(true),
              offValue: .bool(false),
              restart: .finder),
        Tweak(id: "finder.ShowPathbar",
              title: "Show path bar",
              category: .finder,
              domain: "com.apple.finder",
              key: "ShowPathbar",
              onValue: .bool(true),
              offValue: .bool(false),
              restart: .finder),
        Tweak(id: "finder.ShowStatusBar",
              title: "Show status bar",
              category: .finder,
              domain: "com.apple.finder",
              key: "ShowStatusBar",
              onValue: .bool(true),
              offValue: .bool(false),
              restart: .finder),
        Tweak(id: "finder._FXSortFoldersFirst",
              title: "Folders first when sorting",
              category: .finder,
              domain: "com.apple.finder",
              key: "_FXSortFoldersFirst",
              onValue: .bool(true),
              offValue: .bool(false),
              restart: .finder),
        Tweak(id: "finder.FXDefaultSearchScope",
              title: "Search current folder by default",
              subtitle: "Instead of searching the whole Mac",
              category: .finder,
              domain: "com.apple.finder",
              key: "FXDefaultSearchScope",
              onValue: .string("SCcf"),
              restart: .finder),
        Tweak(id: "finder.DSDontWriteNetworkStores",
              title: "No .DS_Store on network drives",
              subtitle: "Takes effect on the next mount",
              category: .finder,
              domain: "com.apple.desktopservices",
              key: "DSDontWriteNetworkStores",
              onValue: .bool(true),
              offValue: .bool(false),
              restart: .finder)
    ]

    static let screenshots: [Tweak] = [
        Tweak(id: "screencapture.location",
              title: "Save location",
              category: .screenshots,
              domain: "com.apple.screencapture",
              key: "location",
              onValue: .string(NSHomeDirectory() + "/Desktop"),
              restart: .systemUIServer,
              control: .folder),
        Tweak(id: "screencapture.type",
              title: "File format",
              category: .screenshots,
              domain: "com.apple.screencapture",
              key: "type",
              onValue: .string("png"),
              restart: .systemUIServer,
              control: .choice([
                  Choice(label: "png", value: .string("png")),
                  Choice(label: "jpg", value: .string("jpg")),
                  Choice(label: "heic", value: .string("heic"))
              ])),
        Tweak(id: "screencapture.disable-shadow",
              title: "No drop shadow",
              category: .screenshots,
              domain: "com.apple.screencapture",
              key: "disable-shadow",
              onValue: .bool(true),
              offValue: .bool(false),
              restart: .systemUIServer),
        Tweak(id: "screencapture.show-thumbnail",
              title: "Skip floating thumbnail",
              subtitle: "Screenshots save straight away",
              category: .screenshots,
              domain: "com.apple.screencapture",
              key: "show-thumbnail",
              onValue: .bool(false),
              offValue: .bool(true),
              restart: .systemUIServer)
    ]

    static let speed: [Tweak] = [
        Tweak(id: "speed.NSAutomaticWindowAnimationsEnabled",
              title: "No window open/close animation",
              category: .speed,
              domain: "NSGlobalDomain",
              key: "NSAutomaticWindowAnimationsEnabled",
              onValue: .bool(false),
              offValue: .bool(true)),
        Tweak(id: "speed.NSWindowResizeTime",
              title: "Instant window resize",
              subtitle: "Only affects apps that animate their own resizes",
              category: .speed,
              domain: "NSGlobalDomain",
              key: "NSWindowResizeTime",
              onValue: .float(0.001)),
        Tweak(id: "speed.KeyRepeat",
              title: "Fast key repeat",
              subtitle: "Faster than System Settings allows",
              category: .speed,
              domain: "NSGlobalDomain",
              key: "KeyRepeat",
              onValue: .int(2)),
        Tweak(id: "speed.InitialKeyRepeat",
              title: "Short repeat delay",
              category: .speed,
              domain: "NSGlobalDomain",
              key: "InitialKeyRepeat",
              onValue: .int(15))
    ]

    // Nothing to restart -- AppKit reads these when a text view is created, so
    // already-running apps keep the old behaviour until they relaunch.
    static let typing: [Tweak] = [
        Tweak(id: "typing.NSAutomaticSpellingCorrectionEnabled",
              title: "Disable autocorrect",
              category: .typing,
              domain: "NSGlobalDomain",
              key: "NSAutomaticSpellingCorrectionEnabled",
              onValue: .bool(false),
              offValue: .bool(true)),
        Tweak(id: "typing.NSAutomaticQuoteSubstitutionEnabled",
              title: "Disable smart quotes",
              category: .typing,
              domain: "NSGlobalDomain",
              key: "NSAutomaticQuoteSubstitutionEnabled",
              onValue: .bool(false),
              offValue: .bool(true)),
        Tweak(id: "typing.NSAutomaticDashSubstitutionEnabled",
              title: "Disable smart dashes",
              category: .typing,
              domain: "NSGlobalDomain",
              key: "NSAutomaticDashSubstitutionEnabled",
              onValue: .bool(false),
              offValue: .bool(true)),
        Tweak(id: "typing.NSAutomaticCapitalizationEnabled",
              title: "Disable auto-capitalise",
              category: .typing,
              domain: "NSGlobalDomain",
              key: "NSAutomaticCapitalizationEnabled",
              onValue: .bool(false),
              offValue: .bool(true)),
        Tweak(id: "typing.ApplePressAndHoldEnabled",
              title: "Hold key to repeat",
              subtitle: "Replaces the accent picker",
              category: .typing,
              domain: "NSGlobalDomain",
              key: "ApplePressAndHoldEnabled",
              onValue: .bool(false),
              offValue: .bool(true))
    ]
}
