import AppKit

struct ClipEntry: Identifiable, Equatable {
    let id = UUID()
    let text: String
    /// PNG bytes when the clip is an image rather than text.
    let imageData: Data?
    let pixelSize: CGSize?
    let date: Date
    /// Set when Switchboard produced the text itself, so a captured or
    /// translated clip is recognisable in the list.
    var note: String?

    var isImage: Bool { imageData != nil }

    var sizeLabel: String {
        guard let pixelSize else { return "Image" }
        return "Image \(Int(pixelSize.width)) by \(Int(pixelSize.height))"
    }

    var preview: String {
        text.trimmingCharacters(in: .whitespacesAndNewlines)
            .replacingOccurrences(of: "\n", with: " ")
    }
    var lineCount: Int { text.split(separator: "\n").count }
}

/// Keeps recent text clips so something copied a few minutes ago is still
/// reachable. Deliberately memory only: a clipboard routinely holds passwords
/// and card numbers, and writing that to disk would turn a convenience into a
/// liability. Quitting Switchboard forgets everything.
final class ClipboardHistory {
    static let limit = 20

    private(set) var entries: [ClipEntry] = []
    private let pasteboard: NSPasteboard
    private var timer: Timer?
    private var lastChangeCount: Int

    /// Password managers and clipboard tools mark their writes with these, and
    /// honouring them is the difference between a history and a leak.
    /// Images are far heavier than text, so they are capped separately.
    static let imageLimit = 8
    static let maximumImageBytes = 8 * 1024 * 1024

    private static let excludedTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
        NSPasteboard.PasteboardType("Pasteboard generator type")
    ]

    var onChange: (() -> Void)?

    init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
        self.lastChangeCount = pasteboard.changeCount
    }

    var isRecording: Bool { timer != nil }

    func setRecording(_ recording: Bool) {
        guard recording != isRecording else { return }
        guard recording else {
            timer?.invalidate()
            timer = nil
            return
        }
        lastChangeCount = pasteboard.changeCount
        let timer = Timer(timeInterval: 0.6, repeats: true) { [weak self] _ in
            self?.capture()
        }
        timer.tolerance = 0.2
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func clear() {
        guard !entries.isEmpty else { return }
        entries.removeAll()
        onChange?()
    }

    func remove(_ entry: ClipEntry) {
        entries.removeAll { $0.id == entry.id }
        onChange?()
    }

    /// Puts an entry back on the clipboard without recording it again.
    @discardableResult
    func copyBack(_ entry: ClipEntry) -> Bool {
        pasteboard.clearContents()
        let ok: Bool
        if let imageData = entry.imageData {
            ok = pasteboard.setData(imageData, forType: .png)
        } else {
            ok = pasteboard.setString(entry.text, forType: .string)
        }
        lastChangeCount = pasteboard.changeCount
        return ok
    }

    /// Records text Switchboard produced, so a capture shows up immediately
    /// rather than waiting for the next poll.
    func record(_ text: String, note: String?) {
        insert(text, note: note)
        lastChangeCount = pasteboard.changeCount
    }

    private func capture() {
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount

        guard let item = pasteboard.pasteboardItems?.first else { return }
        guard Set(item.types).isDisjoint(with: Self.excludedTypes) else { return }

        // Text wins when both are present: styled text carries a TIFF preview
        // alongside its string, and recording that as a picture would be wrong.
        if let text = pasteboard.string(forType: .string),
           !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            insert(text, note: nil)
            return
        }
        if let image = imageData(from: item) {
            insertImage(image.data, pixelSize: image.size)
        }
    }

    private func imageData(from item: NSPasteboardItem) -> (data: Data, size: CGSize)? {
        let candidates: [NSPasteboard.PasteboardType] = [.png, .tiff]
        for type in candidates where item.types.contains(type) {
            guard let raw = item.data(forType: type),
                  raw.count <= Self.maximumImageBytes,
                  let rep = NSBitmapImageRep(data: raw) else { continue }
            let size = CGSize(width: rep.pixelsWide, height: rep.pixelsHigh)
            if type == .png { return (raw, size) }
            guard let png = rep.representation(using: .png, properties: [:]) else { continue }
            return (png, size)
        }
        return nil
    }

    private func insertImage(_ data: Data, pixelSize: CGSize) {
        if let first = entries.first, first.imageData == data { return }
        entries.removeAll { $0.imageData == data }
        entries.insert(ClipEntry(text: "", imageData: data, pixelSize: pixelSize,
                                 date: Date(), note: nil), at: 0)
        // Trim the oldest images first so pictures cannot crowd out text.
        var seen = 0
        entries = entries.filter { entry in
            guard entry.isImage else { return true }
            seen += 1
            return seen <= Self.imageLimit
        }
        if entries.count > Self.limit { entries.removeLast(entries.count - Self.limit) }
        onChange?()
    }

    private func insert(_ text: String, note: String?) {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }
        // Re-copying something already at the top should not duplicate it.
        if let first = entries.first, first.text == text {
            if note != nil, entries[0].note != note { entries[0].note = note; onChange?() }
            return
        }
        entries.removeAll { $0.text == text }
        entries.insert(ClipEntry(text: text, imageData: nil, pixelSize: nil,
                                 date: Date(), note: note), at: 0)
        if entries.count > Self.limit { entries.removeLast(entries.count - Self.limit) }
        onChange?()
    }

    deinit { timer?.invalidate() }
}
